### ISSUE TITLE
更换壁纸卡死

### ISSUE THREAD

**Issue by good-devc** [kaku2015/WeatherAlarmClock#1]
更换壁纸时响应很慢，像是在卡死状态。机型：魅蓝note2，android版本 5.1
ps：UI做的很漂亮

**Comment by karmalove** [comment]
导入你的项目报错，显示布局文件名为大写，还有没有swipeBackActivity，可是我看了它是有导进来的

**Comment by kaku2015** [comment]
@karmalove 没有swipeBackLayout是因为.gitignore配置问题，导致.lib下的文件被git忽略了，已修复更新。布局文件名大写已修复，本地文件明明是小写的，传上去变大写了。。。

**Comment by kaku2015** [comment]
@good-devc 谢谢！你说的问题我用模拟器没有再现出来，我用的两部真机也没有遇见此问题。
你是进入主题页面后卡还是点击了主题界面里的其他图片，主题切换的过程中才卡呢？有时间我再调查调查吧。

**Comment by good-devc** [comment]
@kaku2015 在主题壁纸界面，点击壁纸后没反应，壁纸也没出现选中状态的图标，但貌似不是卡住了，点击左上角的退出图标能正常退出的；点击某一壁纸数次之后，壁纸才切换。。我估计是选图片出现问题吧

**Comment by kaku2015** [comment]
@good-devc 无法复现你说的问题，不太清楚什么原因

**Comment by kaku2015** [comment]
@good-devc 原来是三方库的bug，使用overscroll-decor和GridView一起使用少数机型会出现此问题
