### ISSUE TITLE
SwipeBackLayout的代码怎么没提交。。。

### ISSUE THREAD

**Issue by zhangguobing** [kaku2015/WeatherAlarmClock#2]
SwipeBackLayout的代码怎么没提交。。。

**Comment by kaku2015** [comment]
.gitignore配置问题，导致.lib下的文件被git忽略了，已修复更新。

**Comment by kaku2015** [comment]
@zhangguobing .gitignore配置问题，导致.lib下的文件被git忽略了，已修复更新。
