### ISSUE TITLE
希望作者删除一些自动生成的buid 文件，git pull 时 冲突

### ISSUE THREAD

**Issue by tianshaokai** [kaku2015/WeatherAlarmClock#3]
希望作者代码放到这个WeatherAlarmClock 目录下看的时候更方便

**Comment by kaku2015** [comment]
因为开始项目时，.git文件放在了workspace文件夹下，我后来试过把代码移出workspace文件夹，可是这样做以后我以前的git提交记录都没有了，不知道怎么更改git配置，网上也没找到对应的更改路径方法，你有什么好的方法吗？

自动生成的build文件这方面不太懂，不太清楚哪个没有用...怕删了出问题所以没有清理过。

**Comment by tianshaokai** [comment]
![image](https://cloud.githubusercontent.com/assets/6706496/16252332/dcf676ae-385f-11e6-9042-428e32335a33.png)
我标注的红线的目录都是 没有用的文件 提交的时候 可以使用 .gitignore 文件忽略就行了
以下是工程目录下的 .gitignore 文件内容
.gradle
local.properties
.idea
.DS_Store
build
captures
*.iml

每个模块下也需要有个 .gitignore 文件，内容：
build

**Comment by tianshaokai** [comment]
移动工程到WeatherAlarmClock 这个目录结构，我想是把workspace下的**所有内容(包括.git 这个隐藏文件)**都移动到这个目录下是不是就可以了呢?

**Comment by tianshaokai** [comment]
我想知道你的.git 隐藏文件是在哪个目录下呢workspace 还是WeatherAlarmClock  这个目录呢？ .gitignore 忽略文件是在未提交之前忽略，如果提交了你需要把不需要的文件删除后进程commit，然后再配置.gitignore 再才提交的时候就会成功忽略的

**Comment by tianshaokai** [comment]
我想你的.git 隐藏文件应该是在WeatherAlarmClock这个目录下的 你提交代码应该也是在这个目录下提交的，如果是这样的话就可以把workspace目录下的所有文件剪切到这个目录下，执行git status 的时候你会发现 好多文件都删除了又被重新创建了，其实只是移动了文件位置，并不会删除git 提交历史记录的

**Comment by kaku2015** [comment]
你说的这些方法我都试过，今天又重试了好多次，问题依旧存在，不过还是谢谢你！

**Comment by tianshaokai** [comment]
![image](https://cloud.githubusercontent.com/assets/6706496/16290270/7cbe5f98-392e-11e6-9d26-21d4e1e4694f.png)

我都试过了可以的，不知道作者所说的问题是什么问题，因为工程代码所在的目录名字是可以随便改的，只要截图里 config文件里的 url 远程仓库地址对应了就行了，原来的.git  文件没有被删除 所有的历史记录都是可以找到的

**Comment by kaku2015** [comment]
方便的话留一下你的qq号吧，有时间想向你请教一下，谢谢！

**Comment by kaku2015** [comment]
刚我又试了一下删除没有用的文件然后直接用乌龟提交，可以了，原来是android studio的version control窗口显示错乱的问题。。。但是再有改动version control窗口还是显示蓝色标记，再切换到其他窗口又消失了。。。估计下次重启就没事了。目录问题我再研究研究把，移动后确实git记录都没有了。。。
![Uploading 1.jpg…]()

**Comment by tianshaokai** [comment]
1575640686 这就是我qq
