### ISSUE TITLE
导入project的问题

### ISSUE THREAD

**Issue by lhfly5201314** [kaku2015/WeatherAlarmClock#4]
亲爱的作者，您好！请问一下，为什么在导入project一直有一个库一直报错，就是
'com.afollestad.material-dialogs:commons:0.8.5.9' 这个，按照官方文档配置了也是
can not resolove啊，请问一下，你现在的项目时怎么配置的 ，能发个截图给我吗？
万分感谢！！！

**Comment by kaku2015** [comment]
配置都在代码里的，你下载出来的和我本地的应该一样呀。报错的那个库是不是网络原因没有下载下来呀，你手动下载库然后导入module试试

**Comment by lhfly5201314** [comment]
作者，你好！可能还是我gradle.wrapper的原因，改了一个版本，然后用了几个小时之前官方出的最新版本，这个库的问题解决了。昨天也尝试着把库下下来再导入，但是下下来的库再导入也是各种报错，真是要吐血啊

**Comment by kaku2015** [comment]
你好！是呀，工具方面我也表示很吐血...经常各种问题，现在用最新的2.1.2版本一编译新项目就死机重装也不管用，现在只能用1.5.1...

**Comment by lhfly5201314** [comment]
我就用的2.1.2，没升级前感觉没这么多毛病，升级之后gradle确实没以前好用了。能请教你个问题吗？我是个菜鸟。就是我用studio从github上直接git项目应该和先下载项目然后再导入效果是一样的把？？但是我每次从github上git项目，导入的项目都没有app那种图标，而且类文件都是带了红色的感叹号的那种，也无法部署到手机上，请问这是什么导致的呢》？？谢谢啦

**Comment by kaku2015** [comment]
不太清楚你这个问题，还是问问度娘吧😄

**Comment by lhfly5201314** [comment]
en ,我再上百度Google一下，蛋疼得很

**Comment by zhuzhaolin** [comment]
觉得你这app做的挺好的，很想学习一下但导入android studio没反应- 不能运行 （我导入官方例程时也会这样，android studio 不会去编译）郁闷死了。 请问作者用的是android studio 和gradle是什么版本？

**Comment by kaku2015** [comment]
现在都已更新到最新版本，都是2.1.2

**Comment by zhuzhaolin** [comment]
好的谢谢！！！！！！！！！！！！！！！！！！！！！！！ @kaku2015
